language: objective-c
osx_image: xcode7.3
xcode_sdk: macosx
branches:
  only:
    - master
before_install:
  - carthage bootstrap
script:
  - set -o pipefail && xcodebuild -project "Model Boiler.xcodeproj" -scheme "Model Boiler" -configuration Release -sdk macosx build | xcpretty
