language: objective-c
osx_image: xcode7.2
xcode_sdk: macosx
branches:
  only:
    - master
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose
script:
  - set -o pipefail && xcodebuild -project "Model Boiler.xcodeproj" -scheme "Model Boiler" -configuration Release -sdk macosx build | xcpretty
